server:
  port: 1001
  tomcat:
    max-swallow-size: -1
  max-http-header-size: 10000000
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.jg
spring:
  profiles:
    active: dev