spring:
  datasource:
    druid:
      url: jdbc:mysql://39.97.183.122:3306/blog1?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8
      username: root
      password: yangdeshi
      driver-class-name: com.mysql.cj.jdbc.Driver
      initialSize: 5  #\u521D\u59CB\u5EFA\u7ACB\u8FDE\u63A5\u6570\u91CF
      minIdle: 5  #\u6700\u5C0F\u8FDE\u63A5\u6570\u91CF
      maxActive: 20 #\u6700\u5927\u8FDE\u63A5\u6570\u91CF
      maxWait: 10000  #\u83B7\u53D6\u8FDE\u63A5\u6700\u5927\u7B49\u5F85\u65F6\u95F4\uFF0C\u6BEB\u79D2
      testOnBorrow: true #\u7533\u8BF7\u8FDE\u63A5\u65F6\u68C0\u6D4B\u8FDE\u63A5\u662F\u5426\u6709\u6548
      testOnReturn: false #\u5F52\u8FD8\u8FDE\u63A5\u65F6\u68C0\u6D4B\u8FDE\u63A5\u662F\u5426\u6709\u6548
      timeBetweenEvictionRunsMillis: 60000 #\u914D\u7F6E\u95F4\u9694\u68C0\u6D4B\u8FDE\u63A5\u662F\u5426\u6709\u6548\u7684\u65F6\u95F4\uFF08\u5355\u4F4D\u662F\u6BEB\u79D2\uFF09
      minEvictableIdleTimeMillis: 300000  #\u8FDE\u63A5\u5728\u8FDE\u63A5\u6C60\u7684\u6700\u5C0F\u751F\u5B58\u65F6\u95F4\uFF08\u6BEB\u79D2\uFF09
  ##fastdfs设置
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  data:
    mongodb:
      host: 172.17.175.2
      database: blog1
fdfs:
  so-timeout: 2500
  connect-timeout: 600
  thumb-image:
    width: 100
    height: 100
  tracker-list:
    - 39.97.183.122:22122
upload:
  base-url: http://39.97.183.122/
  allow-types:
    - image/jpeg
    - image/png
    - image/bmp
    - image/gif
    - audio/mpeg